### PR TITLE
fix: add ComponentOptions for Scala SDK

### LINKED ISSUE #445: Duplicate components Options for Scala SDK
yes, we need to duplicate the Options as well.

_Originally posted by @octonato in https://github.com/lightbend/akkaserverless-java-sdk/pull/433#discussion_r712976620_

### PR DESCRIPTION
**Pull request by octonato**
Fixes #445

### CODE REVIEW

File: sdk/java-sdk/src/main/scala/com/akkaserverless/javasdk/impl/view/ViewOptionsImpl.scala [hunk 1]
```diff
@@ -26,5 +26,5 @@ import java.util
  */
 private[akkaserverless] final case class ViewOptionsImpl(override val forwardHeaders: java.util.Set[String])
     extends ViewOptions {
-  def withForwardHeaders(headers: util.Set[String]): ComponentOptions = copy(forwardHeaders = headers)
+  def withForwardHeaders(headers: util.Set[String]): ViewOptions = copy(forwardHeaders = headers)
```
Comment (octonato) [inline sdk/java-sdk/src/main/scala/com/akkaserverless/javasdk/impl/view/ViewOptionsImpl.scala:29]: Here we type the return to be the current impl. I run into a situation in an adapter that required some specialised type, but the method was returns ComponentOptions.

File: sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/EntityOptions.scala [hunk 2]
```diff
@@ -38,11 +40,11 @@ trait EntityOptions extends ComponentOptions {
...
    */
-  def forwardHeaders(): java.util.Set[String]
+  def forwardHeaders: immutable.Set[String]
 
   /**
    * Ask Akka Serverless to forward these headers from the incoming request as metadata headers for the incoming
    * commands. By default no headers except "X-Server-Timing" are forwarded.
    */
-  def withForwardHeaders(headers: java.util.Set[String]): ComponentOptions
+  def withForwardHeaders(headers: immutable.Set[String]): EntityOptions
```
Comment (octonato) [inline sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/EntityOptions.scala:49]: this is the main reason for adding a scala sdk ComponentOptions. Scala developers will pass a Scala Set

File: sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/valueentity/ValueEntityOptions.scala [hunk 3]
```diff
@@ -16,10 +16,13 @@
...
 
+import scala.collection.immutable
+
 import com.akkaserverless.javasdk.PassivationStrategy
 import com.akkaserverless.scalasdk.EntityOptions
 
 /** Root entity options for all value based entities. */
 trait ValueEntityOptions extends EntityOptions {
   def withPassivationStrategy(strategy: PassivationStrategy): ValueEntityOptions
+  def withForwardHeaders(headers: immutable.Set[String]): ValueEntityOptions
```
Comment (octonato) [inline sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/valueentity/ValueEntityOptions.scala:27]: Btw, there is no default impl for this one. I guess this will be added in the process of generating code for ValueEntity

**Review by patriknw — APPROVED** [review]
LGTM

**Review by johanandren — APPROVED** [review]

File: sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/valueentity/ValueEntityOptions.scala (hunk 3 above)
Comment (RayRoestenburg) [reply sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/valueentity/ValueEntityOptions.scala:27]: Is that not in ValueEntityOptionsImpl? (or maybe misunderstanding)

Comment (RayRoestenburg) [reply sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/valueentity/ValueEntityOptions.scala:27]: (so maybe we need another adapter)
